### ISSUE TITLE
Add support for list types

### ISSUE THREAD

**Issue by brettlangdon** [brettlangdon/forge#10]
I originally wanted to add in supports for lists, but scraped it to keep the scope of the project smaller. Eventually would like to add them back in.

Thinking a simple/similar pattern of using `[]` and having it be a generic typed array (rather than a string array or boolean array, etc).

Would look like:
```cfg
list_setting = [
  "value1",
  true,
  null,
  global.reference,
];
```

and the go api could look like:

```go
arrayOfThings, _ := settings.GetList("list_setting")
arrayOfThings.Get(0)  // returns back a generic Value type
arrayOfThings.GetString(0)  // returns back a string value
// also GetBoolean, GetInteger, etc etc, the parameter is the index
arrayOfThings.Length()  // returns back a int size
arrayOfThings.GetValues()  // returns back a go list of values
for value := range arrayOfThings.GetValues() {
    fmt.Println(value)
}
```

Open to any suggestions from others

**Comment by falzm** [comment]
LGTM 👍🏻
