### ISSUE TITLE
Allow single quoted strings

### ISSUE THREAD

**Issue by brettlangdon** [brettlangdon/forge#18]
I am still trying to decide if this is a feature I want to build or not.

It would be nice to be able to use single quotes around a string instead of double quotes, either for those who prefer it or when you have a string that contains a lot of double quotes, rather than escaping them all.

The idea is simple, keep strings working the exact same way, just allow them to be surrounded in single quotes and allow single quotes to be escaped when single quotes are used.

```cfg
single_string = 'some "string" here';
double_string = "some 'string' here";
```

**Comment by lode** [comment]
:+1:
I'm one of those who just prefer single quote style. Especially indeed since double quotes are more common to be actual content. Be it html or natural language.
