### ISSUE TITLE
Why the semi-colon?

### ISSUE THREAD

**Issue by lode** [brettlangdon/forge#20]
Did you explicitly chose for having the semi-colon to end lines?
I don't see it adding much value, except making multiline strings a bit harder / impossible?

Anyway, I would opt for making them optional. Multiline strings could be recognized by their unclosed opening quote.

**Comment by falzm** [comment]
Seconded.

**Comment by brettlangdon** [comment]
It was in part arbitrary and in part easier to write, having the semi-colon be the definitive end of a statement was easier for the first version.

I am more than willing to go back and revisit. I have also been toying with the idea of just implementing a HOCON parser for go, https://github.com/typesafehub/config/blob/master/HOCON.md.

Also, Multiline strings are actually currently supported:

```cfg
multi = "Hello
here are
multiple lines";
```
