### ISSUE TITLE
Numbers in identifiers

### ISSUE THREAD

**Issue by falzm** [brettlangdon/forge#25]
Hi

Any idea if it will be possible to use numbers in identifiers (such as `variable1`, `section2`) someday? I've lost 30mn trying to understand a syntax error before realizing that they're not allowed in idenfiers... It's a silly thing but quite essential, in my opinion.

**Comment by brettlangdon** [comment]
@falzm give `v0.1.6` a try. Allows integers in identifiers, as long as the identifier doesn't begin with one.

**Comment by falzm** [comment]
Well, that's the fastest fix I've ever seen! Thank you :D

**Comment by brettlangdon** [comment]
No problem. Just happen to catch me sitting around watching tv :p
