### ISSUE TITLE
Add support for empty strings

### ISSUE THREAD

**Issue by strfx** [brettlangdon/forge#27]
Providing an empty string, like this:
```
foo = ""
# or
foo = ''
```
causes forge to panic with following message:
```
panic: syntax error line <xy> column <xy>: expected ';' or '
```

When I find the time, I'll take a look at this and create a PR.

Cheers

**Comment by brettlangdon** [comment]
Oh no!

Would happily accept a pull request for a fix :)

Let me know if you aren't able to get to it, I can try and fix this if you'd rather.
