### ISSUE TITLE
Semicolon not optional after lists

### ISSUE THREAD

**Issue by falzm** [brettlangdon/forge#29]
Hi

Looks like semicolon is not that optional on lists...

This works:

```
section {
    subsection {
        ...
        subsubsection {
			some_list = ["a", "b"];
        }
    }
}
```

This doesn't:

```
section {
    subsection {
        ...
        subsubsection {
			some_list = ["a", "b"]
        }
    }
}

[syntax error line <22> column <8>: expected ';' or '
' instead found '}']
```

**Comment by brettlangdon** [comment]
Hey @falzm thank you for reporting. I'll try to carve out some time to look at this (it might be this weekend).

**Comment by falzm** [comment]
Great, thanks!

**Comment by brettlangdon** [comment]
@falzm I have released a fix for this issue, please let me know if you experience any other problems.

**Comment by falzm** [comment]
I confirm it fixes the issue, thank you!
