### ISSUE TITLE
How to merge two sections together?

### ISSUE THREAD

**Issue by jeevatkm** [brettlangdon/forge#32]
Let's say, I have two configuration files named `example1.cfg` & `example2.cfg` and I have section called `prod` in both the config files.

I have to merge `example2.cfg > prod` section into `example1.cfg > prod` section

How to do it?

**Comment by brettlangdon** [comment]
Hmm, not sure there is any easy way to do this other than just manually iterating/merging the two `Section`s together.

I would be willing to accept this as a feature request for merging two `Section`s together.

Maybe something like:

```go
package main

import (
    "github.com/brettlangdon/forge"
)

func main() {
    // Parse a `Section` from `example1.cfg`
    settingsOne, err := forge.ParseFile("example1.cfg")
    if err != nil {
        panic(err)
    }

    // Parse a `Section` from `example2.cfg`
    settingsTwo, err := forge.ParseFile("example2.cfg")
    if err != nil {
        panic(err)
    }

    // Overwrite values in `settingsOne` from those in `settingsTwo`
    settingsOne.Merge(settingsTwo)
}
```

For example, given the following:

```
# example1.cfg
global = "global value";

prod {
  value = "string value";
}
```

```
#example2.cfg

prod {
  value = "new value";
  secret = "shhh";
}
```

By running `settingsOne.Merge(settingsTwo)` in the above example, we would end up with:

```
global = "global value";

prod {
  value = "new value";
  secret = "shhh";  
}
```

**Comment by jeevatkm** [comment]
Your example is right on. I'm happy to do PR.

**Comment by brettlangdon** [comment]
Would be more than happy to accept a PR. Not sure I'd get to it myself until this weekend.

**Comment by jeevatkm** [comment]
No issues. I hope you remember our environment variable [conversation](https://github.com/brettlangdon/forge/issues/13#issuecomment-229080913). I'm using `forge` syntax for my framework. Here is [fork](https://github.com/go-aah/forge) with environment variable and also I have created [thin wrapper](https://github.com/go-aah/config) for framework purpose.

Merge functionality is needed for `aah framework`, so I will take care of this PR, I need your time on review and make PR better :)

**Comment by jeevatkm** [comment]
PR #33 is ready.

**Comment by jeevatkm** [comment]
Since PR #33 is merged. I'm closing this one.
