### ISSUE TITLE
Compatibility with HOCON

### ISSUE THREAD

**Issue by mmindenhall** [brettlangdon/forge#9]
Hello,

Nice library!  I'm just getting started with my first project in Go, and stumbled across it when searching for a Go equivalent to the excellent [typesafe config](https://github.com/typesafehub/config) library I have been using to configure JVM microservices (Play, Java, Apache Camel, Apache Samza, etc.).  Typesafe config is also very cool...it's implemented in Java, with API wrappers for Scala and Clojure, and there are ports to Ruby and Python.  It defines a data format called [HOCON](https://github.com/typesafehub/config/blob/master/HOCON.md), which is a "superset of JSON", and is quite similar to the `forge` format.

It might not be a direction you want to go with `forge`, but I think it would be awesome if there was a Go implementation of HOCON, which would allow for greater configuration file consistency within polyglot organizations (like the one where I work).

But assuming you don't want to implement HOCON support, there are a couple of features that would be nice to "borrow" for inclusion in `forge`:

1.  Support for referencing environment variables (explicitly or conditionally) within a configuration.  For example HOCON uses this syntax:

    ```
    # explicitly reference
    foo = ${FOO}

    # override default only if environment variable defined
    foo = "fooDefault"
    foo = ${?FOO}
    ```
1.  Merging configuration files to create a single configuration.  This is also a cool feature of typesafe config, as it allows for a base configuration (system wide -- e.g., data stores, etc.), and then more specific (application level) configuration files that "overlay" the base configuration (possibly overriding some aspects of the base config).

Many thanks!

**Comment by brettlangdon** [comment]
Cool, I'll give the docs a read over, seems like there could be some cool
features to pick up.

**Comment by brettlangdon** [comment]
Finally gave the docs a read through. I think the main concepts here which I might borrow are:

* Referencing environment variables
* Setting concatenation/merging (I originally wanted to support this)
* Multiline strings

Forge unfortunately probably won't ever support HOCON, that should probably end up being it's own package.
